spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_music?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: s199807
    driver-class-name: com.mysql.cj.jdbc.Driver
